export const API_ENDPOINTS = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    me: "/auth/me",
    forgotPassword: "/auth/forgot-password",
    verifyOtp: "/auth/verify-otp",
    resetPassword: "/auth/reset-password",
    refreshToken: "/auth/refresh",
  },
  dashboard: {
    analytics: "/dashboard/analytics",
    sales: "/dashboard/sales",
    attendance: "/dashboard/attendance",
    performance: "/dashboard/performance",
  },
  employees: {
    list: "/employees",
    detail: (id: string) => `/employees/${id}`,
    create: "/employees",
    update: (id: string) => `/employees/${id}`,
    delete: (id: string) => `/employees/${id}`,
    attendance: "/employees/attendance",
    leaves: "/employees/leaves",
    onboarding: "/employees/onboarding",
  },
  clients: {
    leads: "/clients/leads",
    customers: "/clients/customers",
    companies: "/clients/companies",
    opportunities: "/clients/opportunities",
    activityLog: "/clients/activity-log",
    notes: "/clients/notes",
  },
  projects: {
    tasks: "/projects/tasks",
    overview: "/projects/overview",
    deadlines: "/projects/deadlines",
    milestones: "/projects/milestones",
    reports: "/projects/reports",
  },
  payroll: {
    salaries: "/payroll/salaries",
    invoices: "/payroll/invoices",
    expenses: "/payroll/expenses",
  },
  reports: {
    employeePerformance: "/reports/employee-performance",
    customerEngagement: "/reports/customer-engagement",
    kpi: "/reports/kpi",
  },
  apps: {
    chat: "/apps/chat",
    email: "/apps/email",
    calendar: "/apps/calendar",
    teams: "/apps/teams",
  },
} as const;
