import type { FormField, HrmsModuleConfig } from "@/types/hrms";
import { EMPLOYEE_FORM_SECTIONS } from "@/config/employee-form-sections";

const statusOptions = ["ACTIVE", "INACTIVE"];
const activeInactive = ["Active", "Inactive"];

export const HRMS_MODULES: Record<string, HrmsModuleConfig> = {
  organization: {
    id: "organization",
    title: "Organization",
    section: "Organization Setup",
    tableName: "mst_organization",
    actionLabel: "Add Organization",
    nameKey: "Org_Name",
    modalSize: "xl",
    usesApi: true,
    searchKeys: ["Org_Cd", "Org_Name", "Legal_Name", "Email", "City"],
    columns: [
      { key: "Org_Cd", header: "Org Code" },
      {
        key: "Org_Name",
        header: "Organization Name",
        type: "person",
        subtitleKey: "Org_Cd",
        avatarKey: "Logo_Url",
      },
      { key: "Legal_Name", header: "Legal Name" },
      { key: "Email", header: "Email" },
      { key: "Contact", header: "Contact" },
      { key: "City", header: "City" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Org_Cd", label: "Organization Code", required: true },
      { name: "Org_Name", label: "Organization Name", required: true },
      { name: "Legal_Name", label: "Legal Name" },
      { name: "Regd_No", label: "Registration No" },
      { name: "Email", label: "Email", type: "email" },
      { name: "Contact", label: "Contact", type: "tel" },
      { name: "Website", label: "Website" },
      { name: "Address_line1", label: "Address Line 1", span: "full" },
      { name: "Address_line2", label: "Address Line 2", span: "full" },
      { name: "City", label: "City" },
      { name: "State", label: "State" },
      { name: "Country", label: "Country", defaultValue: "India" },
      { name: "Pincode", label: "Pincode" },
      {
        name: "Logo",
        label: "Logo",
        type: "file",
        accept: "image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp",
        maxSizeMb: 2,
        hint: "JPG, JPEG, PNG, WEBP · max 2 MB · optional",
        previewKey: "Logo_Url",
        fileNameKey: "Logo_Path",
      },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  branches: {
    id: "branches",
    title: "Branch / Office",
    section: "Organization Setup",
    tableName: "mst_branch",
    actionLabel: "Add Branch",
    nameKey: "Branch_Name",
    modalSize: "xl",
    usesApi: true,
    searchKeys: ["Branch_Code", "Branch_Name", "Org_Name", "City", "Email"],
    columns: [
      { key: "Branch_Code", header: "Branch Code" },
      { key: "Branch_Name", header: "Branch Name", type: "person", subtitleKey: "Branch_Code" },
      { key: "Org_Name", header: "Organization" },
      { key: "City", header: "City" },
      { key: "State", header: "State" },
      { key: "Contact", header: "Contact" },
      { key: "Email", header: "Email" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      {
        name: "Org_Id",
        label: "Organization",
        type: "select",
        required: true,
      },
      { name: "Branch_Code", label: "Branch Code", required: true },
      { name: "Branch_Name", label: "Branch Name", required: true },
      { name: "Open_Date", label: "Open Date", type: "date" },
      { name: "Address_line1", label: "Address Line 1", span: "full" },
      { name: "Address_line2", label: "Address Line 2", span: "full" },
      { name: "City", label: "City" },
      { name: "State", label: "State" },
      { name: "Pincode", label: "Pincode" },
      { name: "Contact", label: "Contact", type: "tel" },
      { name: "Email", label: "Email", type: "email" },
      { name: "Latitude", label: "Latitude", type: "number" },
      { name: "Longitude", label: "Longitude", type: "number" },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  departments: {
    id: "departments",
    title: "Department",
    section: "Organization Setup",
    tableName: "mst_department",
    actionLabel: "Add Department",
    nameKey: "Dept_Name",
    usesApi: true,
    searchKeys: ["Dept_Cd", "Dept_Name", "Org_Name"],
    columns: [
      { key: "Dept_Cd", header: "Dept Code" },
      { key: "Dept_Name", header: "Department Name" },
      { key: "Org_Name", header: "Organization" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      {
        name: "Org_Id",
        label: "Organization",
        type: "select",
        required: true,
      },
      { name: "Dept_Cd", label: "Department Code", required: true },
      { name: "Dept_Name", label: "Department Name", required: true },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  designations: {
    id: "designations",
    title: "Designation",
    section: "Organization Setup",
    tableName: "mst_designation",
    actionLabel: "Add Designation",
    nameKey: "Desig_Name",
    usesApi: true,
    searchKeys: ["Desig_Code", "Desig_Name", "Org_Name"],
    columns: [
      { key: "Desig_Code", header: "Designation Code" },
      { key: "Desig_Name", header: "Designation Name" },
      { key: "Org_Name", header: "Organization" },
      { key: "Level_No", header: "Level" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      {
        name: "Org_Id",
        label: "Organization",
        type: "select",
        required: true,
      },
      { name: "Desig_Code", label: "Designation Code", required: true },
      { name: "Desig_Name", label: "Designation Name", required: true },
      { name: "Level_No", label: "Level No", type: "number" },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  grades: {
    id: "grades",
    title: "Grade",
    section: "Organization Setup",
    tableName: "mst_grade",
    actionLabel: "Add Grade",
    nameKey: "Grade_Name",
    usesApi: true,
    searchKeys: ["Grade_Code", "Grade_Name", "Org_Name", "Pay_Band"],
    columns: [
      { key: "Grade_Code", header: "Grade Code" },
      { key: "Grade_Name", header: "Grade Name" },
      { key: "Org_Name", header: "Organization" },
      { key: "Min_salary", header: "Min Salary", type: "currency" },
      { key: "Max_salary", header: "Max Salary", type: "currency" },
      { key: "Pay_Band", header: "Pay Band" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      {
        name: "Org_Id",
        label: "Organization",
        type: "select",
        required: true,
      },
      { name: "Grade_Code", label: "Grade Code", required: true },
      { name: "Grade_Name", label: "Grade Name", required: true },
      { name: "Min_salary", label: "Minimum Salary", type: "number", required: true },
      { name: "Max_salary", label: "Maximum Salary", type: "number", required: true },
      { name: "Pay_Band", label: "Pay Band", span: "full" },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  "employee-categories": {
    id: "employee-categories",
    title: "Employee Category",
    section: "Organization Setup",
    tableName: "mst_employment_status",
    actionLabel: "Add Category",
    nameKey: "Status_name",
    searchKeys: ["Status_code", "Status_name"],
    columns: [
      { key: "Status_code", header: "Category Code" },
      { key: "Status_name", header: "Category Name" },
      { key: "status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Status_code", label: "Category Code", required: true },
      { name: "Status_name", label: "Category Name", required: true },
      { name: "status", label: "Status", type: "select", options: statusOptions },
    ],
  },
  "employment-types": {
    id: "employment-types",
    title: "Employment Type",
    section: "Organization Setup",
    tableName: "mst_employment_type",
    actionLabel: "Add Employment Type",
    nameKey: "Type_name",
    usesApi: true,
    searchKeys: ["Type_code", "Type_name", "Org_Name"],
    columns: [
      { key: "Type_code", header: "Type Code" },
      { key: "Type_name", header: "Type Name" },
      { key: "Org_Name", header: "Organization" },
      { key: "Is_payroll_applicable", header: "Payroll", type: "boolean" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      {
        name: "Org_Id",
        label: "Organization",
        type: "select",
        required: true,
      },
      { name: "Type_code", label: "Type Code", required: true },
      { name: "Type_name", label: "Type Name", required: true },
      {
        name: "Is_payroll_applicable",
        label: "Payroll Applicable",
        type: "checkbox",
        defaultValue: "1",
      },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  "job-types": {
    id: "job-types",
    title: "Job Type",
    section: "Organization Setup",
    tableName: "mst_employment_type",
    actionLabel: "Add Job Type",
    nameKey: "Type_name",
    searchKeys: ["Type_code", "Type_name"],
    columns: [
      { key: "Type_code", header: "Job Type Code" },
      { key: "Type_name", header: "Job Type Name" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Type_code", label: "Job Type Code", required: true },
      { name: "Type_name", label: "Job Type Name", required: true },
      { name: "Status", label: "Status", type: "select", options: statusOptions },
    ],
  },
  shifts: {
    id: "shifts",
    title: "Shift",
    section: "Organization Setup",
    tableName: "mst_work_shift",
    actionLabel: "Add Shift",
    nameKey: "Shift_name",
    usesApi: true,
    searchKeys: ["Shift_code", "Shift_name", "Org_Name"],
    columns: [
      { key: "Shift_code", header: "Shift Code" },
      { key: "Shift_name", header: "Shift Name" },
      { key: "Org_Name", header: "Organization" },
      { key: "Start_time", header: "Start Time", type: "time" },
      { key: "End_time", header: "End Time", type: "time" },
      { key: "Overtime_hr", header: "OT Hours" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      {
        name: "Org_Id",
        label: "Organization",
        type: "select",
        required: true,
      },
      { name: "Shift_code", label: "Shift Code", required: true },
      { name: "Shift_name", label: "Shift Name", required: true },
      { name: "Start_time", label: "Start Time", type: "time", required: true },
      { name: "End_time", label: "End Time", type: "time", required: true },
      { name: "Overtime_hr", label: "Overtime Hours", type: "number" },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  "salary-grades": {
    id: "salary-grades",
    title: "Salary Grade",
    section: "Organization Setup",
    tableName: "mst_grade_salary",
    actionLabel: "Add Salary Grade",
    nameKey: "Grade_Name",
    usesApi: true,
    searchKeys: ["Grade_Name", "Scale_Frm", "Yr_Inc", "Scale_Upto"],
    columns: [
      { key: "Grade_Name", header: "Grade" },
      { key: "Scale_Frm", header: "Scale From", type: "currency" },
      { key: "Yr_Inc", header: "Yearly Increment", type: "currency" },
      { key: "Scale_Upto", header: "Scale Upto", type: "currency" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      {
        name: "Grade_Id",
        label: "Grade",
        type: "select",
        required: true,
      },
      { name: "Scale_Frm", label: "Scale From", type: "number", required: true },
      { name: "Yr_Inc", label: "Yearly Increment", type: "number", required: true },
      { name: "Scale_Upto", label: "Scale Upto", type: "number", required: true },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  employees: {
    id: "employees",
    title: "Employee List",
    section: "Employee Management",
    tableName: "mst_employee",
    actionLabel: "Add Employee",
    nameKey: "Display_name",
    modalSize: "xl",
    searchKeys: ["Employee_code", "First_name", "Last_name", "Email", "Mobile", "Org_Name"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
        avatarKey: "Photo_path",
      },
      { key: "Email", header: "Email" },
      { key: "Mobile", header: "Mobile" },
      { key: "Org_Name", header: "Organization" },
      { key: "Department", header: "Department", filterable: true },
      { key: "Designation", header: "Designation", filterable: true },
      { key: "Date_of_joining", header: "Join Date", type: "date" },
      { key: "Employment_status", header: "Status", type: "status" },
    ],
    formSections: EMPLOYEE_FORM_SECTIONS,
  },
  "employee-profile": {
    id: "employee-profile",
    title: "Employee Profile",
    section: "Employee Management",
    tableName: "mst_employee",
    actionLabel: "Add Profile",
    nameKey: "Display_name",
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name", "Email"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
        avatarKey: "Photo_path",
      },
      { key: "Email", header: "Email" },
      { key: "Mobile", header: "Mobile" },
      { key: "Department", header: "Department", filterable: true },
      { key: "Designation", header: "Designation", filterable: true },
      { key: "Employment_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee Code", required: true },
      { name: "First_name", label: "First Name", required: true },
      { name: "Last_name", label: "Last Name", required: true },
      { name: "Email", label: "Email", type: "email" },
      { name: "Mobile", label: "Mobile", type: "tel" },
      { name: "Department", label: "Department", type: "select", options: ["IT", "HR", "Finance"] },
      { name: "Designation", label: "Designation", type: "select", options: ["Manager", "Executive"] },
      { name: "Employment_status", label: "Status", type: "select", options: activeInactive },
    ],
  },
  onboarding: {
    id: "onboarding",
    title: "Employee Onboarding",
    section: "Employee Management",
    tableName: "mst_employee",
    actionLabel: "Start Onboarding",
    nameKey: "Display_name",
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name"],
    columns: [
      { key: "Employee_code", header: "Employee Code" },
      { key: "Display_name", header: "Employee Name", type: "person", subtitleKey: "Employee_code" },
      { key: "Department", header: "Department", filterable: true },
      { key: "Date_of_joining", header: "Join Date", type: "date" },
      { key: "Onboarding_stage", header: "Stage", filterable: true },
      { key: "Employment_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee Code", required: true },
      { name: "First_name", label: "First Name", required: true },
      { name: "Last_name", label: "Last Name", required: true },
      { name: "Email", label: "Email", type: "email", required: true },
      { name: "Date_of_joining", label: "Joining Date", type: "date", required: true },
      { name: "Department", label: "Department", type: "select", options: ["IT", "HR", "Finance"] },
      { name: "Onboarding_stage", label: "Onboarding Stage", type: "select", options: ["Documents", "Orientation", "Training", "Completed"] },
    ],
  },
  "service-history": {
    id: "service-history",
    title: "Service History",
    section: "Employee Management",
    tableName: "trans_employee_service_history",
    actionLabel: "Add Service Event",
    nameKey: "Employee_name",
    modalSize: "lg",
    searchKeys: ["Employee_name", "Event_type", "Remarks"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Event_type", header: "Event Type", filterable: true },
      { key: "Effective_date", header: "Effective Date", type: "date" },
      { key: "Old_value", header: "Previous" },
      { key: "New_value", header: "Updated To" },
      { key: "Remarks", header: "Remarks" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002", "EMP-1003"], required: true },
      {
        name: "Event_type",
        label: "Event Type",
        type: "select",
        options: ["Joining", "Confirmation", "Transfer", "Promotion", "Salary Revision", "Resignation"],
        required: true,
      },
      { name: "Effective_date", label: "Effective Date", type: "date", required: true },
      { name: "Old_value", label: "Previous Value" },
      { name: "New_value", label: "New Value" },
      { name: "Remarks", label: "Remarks", type: "textarea", span: "full" },
    ],
  },
  "attendance-dashboard": {
    id: "attendance-dashboard",
    title: "Attendance Dashboard",
    section: "Attendance Management",
    tableName: "trans_attendance",
    actionLabel: "Add Record",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Attendance_date"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Attendance_date", header: "Date", type: "date" },
      { key: "Check_in", header: "Check In", type: "time" },
      { key: "Check_out", header: "Check Out", type: "time" },
      { key: "Working_minutes", header: "Working (min)" },
      { key: "Attendance_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Attendance_date", label: "Attendance Date", type: "date", required: true },
      { name: "Check_in", label: "Check In", type: "time" },
      { name: "Check_out", label: "Check Out", type: "time" },
      {
        name: "Attendance_status",
        label: "Status",
        type: "select",
        options: ["Present", "Absent", "Half Day", "Late", "Leave", "Holiday"],
        required: true,
      },
      { name: "Remarks", label: "Remarks", type: "textarea", span: "full" },
    ],
  },
  "daily-attendance": {
    id: "daily-attendance",
    title: "Daily Attendance",
    section: "Attendance Management",
    tableName: "trans_attendance",
    actionLabel: "Mark Attendance",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Attendance_date"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Attendance_date", header: "Date", type: "date" },
      { key: "Shift_name", header: "Shift", filterable: true },
      { key: "Check_in", header: "Check In", type: "time" },
      { key: "Check_out", header: "Check Out", type: "time" },
      { key: "Late_minutes", header: "Late (min)" },
      { key: "Attendance_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Attendance_date", label: "Date", type: "date", required: true },
      { name: "Shift_name", label: "Shift", type: "select", options: ["General Shift", "Night Shift"] },
      { name: "Check_in", label: "Check In", type: "time" },
      { name: "Check_out", label: "Check Out", type: "time" },
      { name: "Attendance_status", label: "Status", type: "select", options: ["Present", "Absent", "Late", "Half Day"], required: true },
    ],
  },
  "attendance-register": {
    id: "attendance-register",
    title: "Attendance Register",
    section: "Attendance Management",
    tableName: "trans_attendance",
    actionLabel: "Add Entry",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Attendance_date"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Attendance_date", header: "Date", type: "date" },
      { key: "Working_minutes", header: "Working (min)" },
      { key: "Overtime_minutes", header: "OT (min)" },
      { key: "Source", header: "Source", filterable: true },
      { key: "Attendance_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Attendance_date", label: "Date", type: "date", required: true },
      { name: "Working_minutes", label: "Working Minutes", type: "number" },
      { name: "Overtime_minutes", label: "Overtime Minutes", type: "number" },
      { name: "Source", label: "Source", type: "select", options: ["Biometric", "Mobile App", "Web Login", "Manual"] },
      { name: "Attendance_status", label: "Status", type: "select", options: ["Present", "Absent", "Leave"], required: true },
    ],
  },
  "check-in-out": {
    id: "check-in-out",
    title: "Check-in / Check-out",
    section: "Attendance Management",
    tableName: "trans_attendance_punch",
    actionLabel: "Add Punch",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Punch_time"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Punch_time", header: "Punch Time" },
      { key: "Punch_type", header: "Punch Type", filterable: true },
      { key: "Source", header: "Source", filterable: true },
      { key: "Device_name", header: "Device" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Punch_time", label: "Punch Time", type: "time", required: true },
      { name: "Punch_type", label: "Punch Type", type: "select", options: ["In", "Out", "Unknown"], required: true },
      { name: "Source", label: "Source", type: "select", options: ["Biometric machine", "Mobile application", "Web login"] },
      { name: "Device_name", label: "Device" },
    ],
  },
  regularization: {
    id: "regularization",
    title: "Attendance Regularization",
    section: "Attendance Management",
    tableName: "trans_attendance",
    actionLabel: "Request Regularization",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Attendance_date"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Attendance_date", header: "Date", type: "date" },
      { key: "Check_in", header: "Requested In", type: "time" },
      { key: "Check_out", header: "Requested Out", type: "time" },
      { key: "Remarks", header: "Reason" },
      { key: "Attendance_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Attendance_date", label: "Date", type: "date", required: true },
      { name: "Check_in", label: "Requested Check In", type: "time" },
      { name: "Check_out", label: "Requested Check Out", type: "time" },
      { name: "Remarks", label: "Reason", type: "textarea", span: "full", required: true },
    ],
  },
  "missing-punch": {
    id: "missing-punch",
    title: "Missing Punch",
    section: "Attendance Management",
    tableName: "trans_attendance_punch",
    actionLabel: "Add Missing Punch",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Punch_time", header: "Expected Punch" },
      { key: "Punch_type", header: "Missing Type" },
      { key: "Source", header: "Source", filterable: true },
      { key: "Attendance_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Punch_time", label: "Expected Punch Time", type: "time", required: true },
      { name: "Punch_type", label: "Missing Punch Type", type: "select", options: ["In", "Out"], required: true },
      { name: "Remarks", label: "Remarks", type: "textarea", span: "full" },
    ],
  },
  overtime: {
    id: "overtime",
    title: "Overtime",
    section: "Attendance Management",
    tableName: "trans_attendance",
    actionLabel: "Add Overtime",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Attendance_date", header: "Date", type: "date" },
      { key: "Overtime_minutes", header: "OT Minutes" },
      { key: "Shift_name", header: "Shift", filterable: true },
      { key: "Remarks", header: "Remarks" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Attendance_date", label: "Date", type: "date", required: true },
      { name: "Overtime_minutes", label: "Overtime Minutes", type: "number", required: true },
      { name: "Remarks", label: "Remarks", type: "textarea", span: "full" },
    ],
  },
  "attendance-shifts": {
    id: "attendance-shifts",
    title: "Shift Management",
    section: "Attendance Management",
    tableName: "trans_employee_shift",
    actionLabel: "Assign Shift",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Shift_name"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Shift_name", header: "Shift", filterable: true },
      { key: "From_date", header: "From Date", type: "date" },
      { key: "To_date", header: "To Date", type: "date" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Shift_name", label: "Shift", type: "select", options: ["General Shift", "Night Shift"], required: true },
      { name: "From_date", label: "From Date", type: "date", required: true },
      { name: "To_date", label: "To Date", type: "date" },
    ],
  },
  "attendance-rules": {
    id: "attendance-rules",
    title: "Attendance Rules",
    section: "Attendance Management",
    tableName: "mst_work_shift",
    actionLabel: "Add Rule",
    nameKey: "Rule_name",
    searchKeys: ["Rule_name"],
    columns: [
      { key: "Rule_name", header: "Rule Name" },
      { key: "Grace_minutes", header: "Grace (min)" },
      { key: "Min_working_hours", header: "Min Hours" },
      { key: "Overtime_after", header: "OT After (hrs)" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Rule_name", label: "Rule Name", required: true },
      { name: "Grace_minutes", label: "Grace Minutes", type: "number" },
      { name: "Min_working_hours", label: "Minimum Working Hours", type: "number" },
      { name: "Overtime_after", label: "Overtime After (hours)", type: "number" },
      { name: "Status", label: "Status", type: "select", options: statusOptions },
    ],
  },
  holidays: {
    id: "holidays",
    title: "Holidays",
    section: "Attendance Management",
    tableName: "mst_holiday",
    actionLabel: "Add Holiday",
    nameKey: "Holiday_name",
    searchKeys: ["Holiday_name", "Holiday_date"],
    columns: [
      { key: "Holiday_date", header: "Date", type: "date" },
      { key: "Holiday_name", header: "Holiday Name" },
      { key: "Holiday_type", header: "Type", filterable: true },
      { key: "Is_optional", header: "Optional", type: "boolean" },
    ],
    formFields: [
      { name: "Holiday_date", label: "Holiday Date", type: "date", required: true },
      { name: "Holiday_name", label: "Holiday Name", required: true },
      {
        name: "Holiday_type",
        label: "Holiday Type",
        type: "select",
        options: ["NATIONAL", "FESTIVAL", "REGIONAL", "OPTIONAL", "OTHER"],
        required: true,
      },
      { name: "Is_optional", label: "Optional Holiday", type: "checkbox" },
    ],
  },
  "weekly-off": {
    id: "weekly-off",
    title: "Weekly Off",
    section: "Attendance Management",
    tableName: "mst_work_shift",
    actionLabel: "Add Weekly Off",
    nameKey: "Day_name",
    searchKeys: ["Day_name", "Branch_Name"],
    columns: [
      { key: "Day_name", header: "Day" },
      { key: "Branch_Name", header: "Branch", filterable: true },
      { key: "Off_type", header: "Off Type", filterable: true },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      {
        name: "Day_name",
        label: "Weekly Off Day",
        type: "select",
        options: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        required: true,
      },
      { name: "Branch_Name", label: "Branch", type: "select", options: ["All Branches", "Head Office", "Branch 1"] },
      { name: "Off_type", label: "Off Type", type: "select", options: ["Full Day", "Alternate Saturday"] },
      { name: "Status", label: "Status", type: "select", options: statusOptions },
    ],
  },
};

export function getHrmsModule(moduleId: string): HrmsModuleConfig {
  const config = HRMS_MODULES[moduleId];
  if (!config) {
    throw new Error(`Unknown HRMS module: ${moduleId}`);
  }
  return config;
}

export function getModuleFilterFields(config: HrmsModuleConfig) {
  return config.columns
    .filter((column) => column.filterable || column.type === "status")
    .map((column) => ({ key: column.key, label: column.header }));
}

export function getModuleFormFields(config: HrmsModuleConfig): FormField[] {
  if (config.formSections?.length) {
    return config.formSections.flatMap((section) => section.fields);
  }
  return config.formFields ?? [];
}
