import type { FormField, HrmsModuleConfig } from "@/types/hrms";
import { EMPLOYEE_FORM_SECTIONS } from "@/config/employee-form-sections";
import {
  ATTENDANCE_RULE_FORM_SECTIONS,
  ATTENDANCE_SOURCE_TYPES,
  ATTENDANCE_STATUS_OPTIONS,
} from "@/config/attendance-form-sections";

const statusOptions = ["ACTIVE", "INACTIVE"];
const activeInactive = ["Active", "Inactive"];

export const HRMS_MODULES: Record<string, HrmsModuleConfig> = {
  organization: {
    id: "organization",
    title: "Organization",
    section: "Organization Setup",
    tableName: "mst_organization",
    nameKey: "Org_Name",
    modalSize: "xl",
    usesApi: true,
    disableEditSubmit: true,
    searchKeys: ["Org_Cd", "Org_Name", "Legal_Name", "Email", "City"],
    columns: [
      { key: "Org_Cd", header: "Org Code" },
      {
        key: "Org_Name",
        header: "Organization Name",
        type: "person",
        avatarKey: "Logo_Url",
      },
      { key: "Legal_Name", header: "Legal Name" },
      { key: "Email", header: "Email" },
      { key: "Contact", header: "Contact" },
      { key: "City", header: "City" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      // { name: "Org_Cd", label: "Organization Code", required: true },
      // { name: "Org_Name", label: "Organization Name", required: true },
      { name: "Legal_Name", label: "Legal Name" },
      { name: "Regd_No", label: "Registration No" },
      { name: "Email", label: "Email", type: "email" },
      { name: "Contact", label: "Contact", type: "tel" },
      { name: "Website", label: "Website" },
      { name: "Address_line1", label: "Address Line 1", span: "full" },
      { name: "Address_line2", label: "Address Line 2", span: "full" },
      { name: "City", label: "City" },
      { name: "State", label: "State" },
      { name: "Country", label: "Country", defaultValue: "India" },
      { name: "Pincode", label: "Pincode" },
      {
        name: "Logo",
        label: "Logo",
        type: "file",
        accept: "image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp",
        maxSizeMb: 2,
        hint: "JPG, JPEG, PNG, WEBP · max 2 MB · optional",
        previewKey: "Logo_Url",
        fileNameKey: "Logo_Path",
      },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  branches: {
    id: "branches",
    title: "Branch / Office",
    section: "Organization Setup",
    tableName: "mst_branch",
    // actionLabel: "Add Branch",
    nameKey: "Branch_Name",
    modalSize: "xl",
    usesApi: true,
    disableEditSubmit: true,
    searchKeys: ["Branch_Code", "Branch_Name", "Org_Name", "City", "Email"],
    columns: [
      { key: "Branch_Code", header: "Branch Code" },
      { key: "Branch_Name", header: "Branch Name", type: "person" },
      // { key: "Org_Name", header: "Organization" },
      { key: "City", header: "City" },
      { key: "State", header: "State" },
      { key: "Contact", header: "Contact" },
      { key: "Email", header: "Email" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      // {
      //   name: "Org_Id",
      //   label: "Organization",
      //   type: "select",
      //   required: true,
      // },
      // { name: "Branch_Code", label: "Branch Code", required: true },
      { name: "Branch_Name", label: "Branch Name", required: true },
      { name: "Open_Date", label: "Open Date", type: "date" },
      { name: "Address_line1", label: "Address Line 1", span: "full" },
      { name: "Address_line2", label: "Address Line 2", span: "full" },
      { name: "City", label: "City" },
      { name: "State", label: "State" },
      { name: "Pincode", label: "Pincode" },
      { name: "Contact", label: "Contact", type: "tel" },
      { name: "Email", label: "Email", type: "email" },
      { name: "Latitude", label: "Latitude", type: "number" },
      { name: "Longitude", label: "Longitude", type: "number" },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  departments: {
    id: "departments",
    title: "Department",
    section: "Organization Setup",
    tableName: "mst_department",
    actionLabel: "Add Department",
    nameKey: "Dept_Name",
    usesApi: true,
    searchKeys: ["Dept_Cd", "Dept_Name", "Org_Name"],
    columns: [
      { key: "Dept_Cd", header: "Dept Code" },
      { key: "Dept_Name", header: "Department Name" },
      { key: "Org_Name", header: "Organization" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      // {
      //   name: "Org_Id",
      //   label: "Organization",
      //   type: "select",
      //   required: true,
      // },
      // { name: "Dept_Cd", label: "Department Code", required: true },
      { name: "Dept_Name", label: "Department Name", required: true },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  designations: {
    id: "designations",
    title: "Designation",
    section: "Organization Setup",
    tableName: "mst_designation",
    actionLabel: "Add Designation",
    nameKey: "Desig_Name",
    usesApi: true,
    searchKeys: ["Desig_Code", "Desig_Name", "Org_Name"],
    columns: [
      { key: "Desig_Code", header: "Designation Code" },
      { key: "Desig_Name", header: "Designation Name" },
      // { key: "Org_Name", header: "Organization" },
      { key: "Level_No", header: "Level" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      // {
      //   name: "Org_Id",
      //   label: "Organization",
      //   type: "select",
      //   required: true,
      // },
      // { name: "Desig_Code", label: "Designation Code", required: true },
      { name: "Desig_Name", label: "Designation Name", required: true },
      { name: "Level_No", label: "Level No", type: "number" },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  grades: {
    id: "grades",
    title: "Grade",
    section: "Organization Setup",
    tableName: "mst_grade",
    actionLabel: "Add Grade",
    nameKey: "Grade_Name",
    usesApi: true,
    searchKeys: ["Grade_Code", "Grade_Name", "Org_Name", "Pay_Band"],
    columns: [
      { key: "Grade_Code", header: "Grade Code" },
      { key: "Grade_Name", header: "Grade Name" },
      // { key: "Org_Name", header: "Organization" },
      { key: "Min_salary", header: "Min Salary", type: "currency" },
      { key: "Max_salary", header: "Max Salary", type: "currency" },
      { key: "Pay_Band", header: "Pay Band" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      // {
      //   name: "Org_Id",
      //   label: "Organization",
      //   type: "select",
      //   required: true,
      // },
      // { name: "Grade_Code", label: "Grade Code", required: true },
      { name: "Grade_Name", label: "Grade Name", required: true },
      { name: "Min_salary", label: "Minimum Salary", type: "number", required: true },
      { name: "Max_salary", label: "Maximum Salary", type: "number", required: true },
      { name: "Pay_Band", label: "Pay Band", span: "full" },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  "employee-status": {
    id: "employee-status",
    title: "Employee Status",
    section: "Organization Setup",
    tableName: "mst_employment_status",
    actionLabel: "Add Status",
    nameKey: "Status_name",
    usesApi: true,
    searchKeys: [
      "Status_name",
    ],

    columns: [
      {
        key: "Status_name",
        header: "Status Name",
      },
      {
        key: "status",
        header: "Status",
        type: "status",
      },
    ],

    formFields: [
      {
        name: "Status_name",
        label: "Status Name",
        required: true,
        placeholder: "e.g. Active",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: [
          {
            value: "Active",
            label: "Active",
          },
          {
            value: "Inactive",
            label: "Inactive",
          },
        ],
        defaultValue: "Active",
      },
    ],
  },
  "employment-types": {
    id: "employment-types",
    title: "Employment Type",
    section: "Organization Setup",
    tableName: "mst_employment_type",
    actionLabel: "Add Employment Type",
    nameKey: "Type_name",
    usesApi: true,
    searchKeys: ["Type_code", "Type_name", "Org_Name"],
    columns: [
      { key: "Type_code", header: "Type Code" },
      { key: "Type_name", header: "Type Name" },
      // { key: "Org_Name", header: "Organization" },
      { key: "Is_payroll_applicable", header: "Payroll", type: "boolean" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      // {
      //   name: "Org_Id",
      //   label: "Organization",
      //   type: "select",
      //   required: true,
      // },
      // { name: "Type_code", label: "Type Code", required: true },
      { name: "Type_name", label: "Type Name", required: true },
      {
        name: "Is_payroll_applicable",
        label: "Payroll Applicable",
        type: "checkbox",
        defaultValue: "1",
      },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  "job-types": {
    id: "job-types",
    title: "Job Type",
    section: "Organization Setup",
    tableName: "mst_employment_type",
    actionLabel: "Add Job Type",
    nameKey: "Type_name",
    searchKeys: ["Type_code", "Type_name"],
    columns: [
      { key: "Type_code", header: "Job Type Code" },
      { key: "Type_name", header: "Job Type Name" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Type_code", label: "Job Type Code", required: true },
      { name: "Type_name", label: "Job Type Name", required: true },
      { name: "Status", label: "Status", type: "select", options: statusOptions },
    ],
  },
  shifts: {
    id: "shifts",
    title: "Shift",
    section: "Organization Setup",
    tableName: "mst_work_shift",
    actionLabel: "Add Shift",
    nameKey: "Shift_name",
    usesApi: true,
    searchKeys: ["Shift_code", "Shift_name", "Org_Name"],
    columns: [
      { key: "Shift_code", header: "Shift Code" },
      { key: "Shift_name", header: "Shift Name" },
      // { key: "Org_Name", header: "Organization" },
      { key: "Start_time", header: "Start Time", type: "time" },
      { key: "End_time", header: "End Time", type: "time" },
      { key: "Overtime_hr", header: "OT Hours" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      // {
      //   name: "Org_Id",
      //   label: "Organization",
      //   type: "select",
      //   required: true,
      // },
      // { name: "Shift_code", label: "Shift Code", required: true },
      { name: "Shift_name", label: "Shift Name", required: true },
      { name: "Start_time", label: "Start Time", type: "time", required: true },
      { name: "End_time", label: "End Time", type: "time", required: true },
      { name: "Overtime_hr", label: "Overtime Hours", type: "number" },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  "salary-grades": {
    id: "salary-grades",
    title: "Salary Grade",
    section: "Organization Setup",
    tableName: "mst_grade_salary",
    actionLabel: "Add Salary Grade",
    nameKey: "Grade_Name",
    usesApi: true,
    searchKeys: ["Grade_Name", "Scale_Frm", "Yr_Inc", "Scale_Upto"],
    columns: [
      { key: "Grade_Name", header: "Grade" },
      { key: "Scale_Frm", header: "Scale From", type: "currency" },
      { key: "Yr_Inc", header: "Yearly Increment", type: "currency" },
      { key: "Scale_Upto", header: "Scale Upto", type: "currency" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      {
        name: "Grade_Id",
        label: "Grade",
        type: "select",
        required: true,
      },
      { name: "Scale_Frm", label: "Scale From", type: "number", required: true },
      { name: "Yr_Inc", label: "Yearly Increment", type: "number", required: true },
      { name: "Scale_Upto", label: "Scale Upto", type: "number", required: true },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  "asset-types": {
    id: "asset-types",
    title: "Asset Type Master",
    section: "Organization Setup",
    tableName: "mst_asset_type",
    actionLabel: "Add Asset Type",
    nameKey: "Type_name",
    modalSize: "md",
    usesApi: true,
    statusToggle: false,
    searchKeys: ["Type_id", "Type_name"],
    columns: [
      { key: "Type_id", header: "Type ID" },
      { key: "Type_name", header: "Asset Type" },
    ],
    formFields: [
      { name: "Type_name", label: "Asset Type Name", required: true },
    ],
  },
  assets: {
    id: "assets",
    title: "Asset Master",
    section: "Organization Setup",
    tableName: "mst_asset",
    actionLabel: "Add Asset",
    nameKey: "Asset_code",
    modalSize: "lg",
    usesApi: true,


    searchKeys: [
      "Asset_id",
      "Asset_code",
      "Asset_type_name",
      "Serial_number",
    ],

    columns: [
      // { key: "Asset_id", header: "Asset ID" },
      { key: "Asset_code", header: "Asset Code" },
      { key: "Asset_type_name", header: "Asset Type", filterable: true },
      { key: "Serial_number", header: "Serial Number" },
      { key: "Purchase_date", header: "Purchase Date", type: "date" },
      { key: "Purchase_cost", header: "Purchase Cost", type: "currency" },
      { key: "Warranty_expiry", header: "Warranty Expiry", type: "date" },
      { key: "Asset_status", header: "Status", type: "status", filterable: true },
      { key: "Remarks", header: "Remarks" },
    ],

    formFields: [
      {
        name: "Asset_type",
        label: "Asset Type",
        type: "select",
        required: true,
        options: [], // Populated dynamically via MasterDataPage
      },
      {
        name: "Asset_code",
        label: "Asset Code",
        required: true,
        placeholder: "e.g. LAP-001",
      },
      {
        name: "Serial_number",
        label: "Serial Number",
      },
      {
        name: "Purchase_date",
        label: "Purchase Date",
        type: "date",
      },
      {
        name: "Purchase_cost",
        label: "Purchase Cost",
        type: "number",
      },
      {
        name: "Warranty_expiry",
        label: "Warranty Expiry",
        type: "date",
      },
      {
        name: "Asset_status",
        label: "Status",
        type: "select",
        options: [
          { value: "1", label: "Active" },
          { value: "0", label: "Inactive" },
        ],
        defaultValue: "1",
      },
      {
        name: "Remarks",
        label: "Remarks",
        type: "textarea",
        span: "full",
      },
    ],
  },
  devices: {
    id: "devices",
    title: "Device Setup",
    section: "Organization Setup",
    tableName: "mst_devices",
    actionLabel: "Add Device",
    nameKey: "Device_name",
    modalSize: "lg",
    usesApi: true,
    searchKeys: [
      "Device_name",
      "Ip_address",
      "Serial_no",
      "Location",
      "Device_model",
    ],
    columns: [
      { key: "Device_name", header: "Device Name" },
      { key: "Ip_address", header: "IP Address" },
      { key: "Port", header: "Port" },
      { key: "Location", header: "Location", filterable: true },
      { key: "Device_model", header: "Model" },
      { key: "Serial_no", header: "Serial No." },
      { key: "Last_sync_time", header: "Last Sync" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      {
        name: "Device_name",
        label: "Device Name",
        required: true,
        placeholder: "e.g. ZKTeco Main Gate",
        span: "full",
      },
      {
        name: "Ip_address",
        label: "IP Address",
        required: true,
        placeholder: "e.g. 192.168.0.10",
      },
      {
        name: "Port",
        label: "Port",
        type: "number",
        placeholder: "4370",
        defaultValue: "4370",
      },
      {
        name: "Location",
        label: "Location",
        placeholder: "e.g. Head Office",
      },
      {
        name: "Device_model",
        label: "Device Model",
        placeholder: "e.g. F09",
      },
      {
        name: "Serial_no",
        label: "Serial Number",
        placeholder: "e.g. NYU7253500318",
      },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: [
          { value: "Active", label: "Active" },
          { value: "Inactive", label: "Inactive" },
        ],
        defaultValue: "Active",
      },
    ],
  },
  employees: {
    id: "employees",
    title: "Employee List",
    section: "Employee Management",
    tableName: "mst_employee",
    actionLabel: "Add Employee",
    nameKey: "Display_name",
    usesApi: true,
    modalSize: "xl",
    searchKeys: ["Employee_code", "First_name", "Last_name", "Email", "Mobile", "Org_Name"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
        avatarKey: "Photo_path",
      },
      { key: "Email", header: "Email" },
      { key: "Mobile", header: "Mobile" },
      // { key: "Org_Name", header: "Organization" },
      { key: "Department", header: "Department", filterable: true },
      { key: "Designation", header: "Designation", filterable: true },
      { key: "Date_of_joining", header: "Join Date", type: "date" },
      { key: "Employment_status_name", header: "Emp Status", filterable: true },
      { key: "Status", header: "Status", type: "status", filterable: true },
    ],
    formSections: EMPLOYEE_FORM_SECTIONS,
  },
  "employee-register": {
    id: "employee-register",
    title: "Employee Register",
    section: "Employee Reports",
    tableName: "mst_employee",
    actionLabel: "Add Employee",
    nameKey: "Display_name",
    usesApi: true,
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name", "Branch", "Department", "Designation", "Category"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
      },
      { key: "Branch", header: "Branch", filterable: true },
      { key: "Department", header: "Department", filterable: true },
      { key: "Designation", header: "Designation", filterable: true },
      { key: "Category", header: "Category", filterable: true },
      { key: "Date_of_joining", header: "Join Date", type: "date" },
      { key: "Status", header: "Status", type: "status", filterable: true },
    ],
  },
  "employee-service-history-report": {
    id: "employee-service-history-report",
    title: "Service History",
    section: "Employee Reports",
    tableName: "mst_employee",
    actionLabel: "Export",
    nameKey: "Display_name",
    usesApi: true,
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name", "Event_type", "Remarks"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
      },
      { key: "Event_type", header: "Event", filterable: true },
      { key: "Effective_date", header: "Effective Date", type: "date" },
      { key: "Old_value", header: "Previous Value" },
      { key: "New_value", header: "New Value" },
      { key: "Remarks", header: "Remarks" },
    ],
  },
  "employee-attendance-report": {
    id: "employee-attendance-report",
    title: "Employee-wise Attendance",
    section: "Attendance Reports",
    tableName: "trans_attendance",
    actionLabel: "Export",
    nameKey: "Display_name",
    usesApi: true,
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name", "Status"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
      },
      { key: "Date", header: "Date", type: "date" },
      { key: "In_time", header: "Check In" },
      { key: "Out_time", header: "Check Out" },
      { key: "Total_hours", header: "Total Hours" },
      { key: "Status", header: "Status", type: "status", filterable: true },
    ],
  },
  "late-coming-report": {
    id: "late-coming-report",
    title: "Late Coming Report",
    section: "Attendance Reports",
    tableName: "trans_attendance",
    actionLabel: "Export",
    nameKey: "Display_name",
    usesApi: true,
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name", "Status"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
      },
      { key: "Date", header: "Date", type: "date" },
      { key: "In_time", header: "Check In" },
      { key: "Late_minutes", header: "Late (Mins)" },
      { key: "Status", header: "Status", type: "status", filterable: true },
    ],
  },
  "early-leaving-report": {
    id: "early-leaving-report",
    title: "Early Leaving Report",
    section: "Attendance Reports",
    tableName: "trans_attendance",
    actionLabel: "Export",
    nameKey: "Display_name",
    usesApi: true,
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name", "Status"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
      },
      { key: "Attendance_date", header: "Date", type: "date" },
      { key: "Shift_name", header: "Shift" },
      { key: "Check_out", header: "Check Out" },
      { key: "Early_departure_minutes", header: "Early (Mins)" },
      { key: "Attendance_status", header: "Status", type: "status", filterable: true },
    ],
  },
  "attendance-summary-report": {
    id: "attendance-summary-report",
    title: "Attendance Summary",
    section: "Attendance Reports",
    tableName: "trans_attendance",
    actionLabel: "Export",
    nameKey: "Display_name",
    usesApi: true,
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
      },
      { key: "Total_Present", header: "Present" },
      { key: "Total_Absent", header: "Absent" },
      { key: "Total_Late", header: "Late Days" },
      { key: "Total_Leave", header: "Leave Days" },
      { key: "Month", header: "Month", filterable: true },
    ],
  },
  "leave-register-report": {
    id: "leave-register-report",
    title: "Leave Register",
    section: "Leave Reports",
    tableName: "trans_leave",
    actionLabel: "Export",
    nameKey: "Display_name",
    usesApi: true,
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name", "Leave_type", "Status"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
      },
      { key: "Leave_type", header: "Leave Type", filterable: true },
      { key: "From_date", header: "From Date", type: "date" },
      { key: "To_date", header: "To Date", type: "date" },
      { key: "Total_days", header: "Total Days" },
      { key: "Status", header: "Status", type: "status", filterable: true },
    ],
  },
  "employee-leave-report": {
    id: "employee-leave-report",
    title: "Employee-wise Leave",
    section: "Leave Reports",
    tableName: "trans_leave",
    actionLabel: "Export",
    nameKey: "Display_name",
    usesApi: true,
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name", "Leave_type"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
      },
      { key: "Leave_type", header: "Leave Type", filterable: true },
      { key: "Total_Allocated", header: "Allocated Days" },
      { key: "Total_Used", header: "Used Days" },
      { key: "Total_Balance", header: "Balance Days" },
    ],
  },
  "employee-profile": {
    id: "employee-profile",
    title: "Employee Profile",
    section: "Employee Management",
    tableName: "mst_employee",
    actionLabel: "Add Profile",
    nameKey: "Display_name",
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name", "Email"],
    columns: [
      {
        key: "Display_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
        avatarKey: "Photo_path",
      },
      { key: "Email", header: "Email" },
      { key: "Mobile", header: "Mobile" },
      { key: "Department", header: "Department", filterable: true },
      { key: "Designation", header: "Designation", filterable: true },
      { key: "Employment_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee Code", required: true },
      { name: "First_name", label: "First Name", required: true },
      { name: "Last_name", label: "Last Name", required: true },
      { name: "Email", label: "Email", type: "email" },
      { name: "Mobile", label: "Mobile", type: "tel" },
      { name: "Department", label: "Department", type: "select", options: ["IT", "HR", "Finance"] },
      { name: "Designation", label: "Designation", type: "select", options: ["Manager", "Executive"] },
      { name: "Employment_status", label: "Status", type: "select", options: activeInactive },
    ],
  },
  onboarding: {
    id: "onboarding",
    title: "Employee Onboarding",
    section: "Employee Management",
    tableName: "mst_employee",
    actionLabel: "Start Onboarding",
    nameKey: "Display_name",
    modalSize: "xl",
    searchKeys: ["Employee_code", "Display_name"],
    columns: [
      { key: "Employee_code", header: "Employee Code" },
      { key: "Display_name", header: "Employee Name", type: "person", subtitleKey: "Employee_code" },
      { key: "Department", header: "Department", filterable: true },
      { key: "Date_of_joining", header: "Join Date", type: "date" },
      { key: "Onboarding_stage", header: "Stage", filterable: true },
      { key: "Employment_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee Code", required: true },
      { name: "First_name", label: "First Name", required: true },
      { name: "Last_name", label: "Last Name", required: true },
      { name: "Email", label: "Email", type: "email", required: true },
      { name: "Date_of_joining", label: "Joining Date", type: "date", required: true },
      { name: "Department", label: "Department", type: "select", options: ["IT", "HR", "Finance"] },
      { name: "Onboarding_stage", label: "Onboarding Stage", type: "select", options: ["Documents", "Orientation", "Training", "Completed"] },
    ],
  },
  "service-history": {
    id: "service-history",
    title: "Service History",
    section: "Employee Management",
    tableName: "trans_employee_service_history",
    actionLabel: "Add Service Event",
    nameKey: "Employee_name",
    modalSize: "lg",
    searchKeys: ["Employee_name", "Event_type", "Remarks"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Event_type", header: "Event Type", filterable: true },
      { key: "Effective_date", header: "Effective Date", type: "date" },
      { key: "Old_value", header: "Previous" },
      { key: "New_value", header: "Updated To" },
      { key: "Remarks", header: "Remarks" },
    ],
    formFields: [
      {
        name: "Employee_id",
        label: "Employee",
        type: "select",
        required: true,
        options: [],
      },
      {
        name: "Event_type_code",
        label: "Event Type",
        type: "select",
        required: true,
        options: [],
      },
      { name: "Effective_date", label: "Effective Date", type: "date", required: true },
      {
        name: "Old_Id",
        label: "Previous Value",
        type: "select",
        options: [],
      },
      {
        name: "New_Id",
        label: "Updated To",
        type: "select",
        options: [],
      },
      { name: "Old_Amount", label: "Previous Amount", type: "number" },
      { name: "New_Amount", label: "New Amount", type: "number" },
      { name: "Remarks", label: "Remarks", type: "textarea", span: "full" },
    ],
  },
  "asset-allocation": {
    id: "asset-allocation",
    title: "Asset Allocation",
    section: "Employee Management",
    tableName: "trans_employee_asset",
    actionLabel: "Allocate Asset",
    nameKey: "Employee_name",
    modalSize: "lg",
    searchKeys: [
      "Employee_name",
      "Employee_code",
      "Asset_code",
      "Asset_name",
      "Asset_type",
      "Serial_number",
    ],
    columns: [
      {
        key: "Employee_name",
        header: "Employee",
        type: "person",
        subtitleKey: "Employee_code",
        avatarKey: "Photo_path",
      },
      { key: "Asset_code", header: "Asset Code" },
      { key: "Asset_name", header: "Asset" },
      { key: "Asset_type", header: "Type", filterable: true },
      { key: "Serial_number", header: "Serial Number" },
      { key: "Allocation_date", header: "Allocated On", type: "date" },
      { key: "Return_date", header: "Return Date", type: "date" },
      { key: "Allocation_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      {
        name: "Employee_id",
        label: "Employee",
        type: "select",
        required: true,
        options: [],
      },
      {
        name: "Asset_id",
        label: "Asset",
        type: "select",
        required: true,
        options: [],
      },
      {
        name: "Allocation_date",
        label: "Allocation Date",
        type: "date",
        required: true,
      },
      {
        name: "Return_date",
        label: "Actual Return Date",
        type: "date",
      },
      {
        name: "Condition",
        label: "Issue Condition",
        type: "select",
        options: ["New", "Good", "Fair", "Damaged"],
        defaultValue: "Good",
      },
      {
        name: "Return_condition",
        label: "Return Condition",
        type: "select",
        options: ["New", "Good", "Fair", "Damaged"],
      },
      {
        name: "Allocation_status",
        label: "Status",
        type: "select",
        options: ["Allocated", "Returned"],
        defaultValue: "Allocated",
      },
      {
        name: "Remarks",
        label: "Remarks",
        type: "textarea",
        span: "full",
        placeholder: "Allocation notes, accessories issued, or return comments",
      },
    ],
  },
  "attendance-dashboard": {
    id: "attendance-dashboard",
    title: "Attendance Dashboard",
    section: "Attendance Management",
    tableName: "trans_attendance",
    actionLabel: "Add Record",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Employee_code", "Attendance_date", "Attendance_status"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Attendance_date", header: "Date", type: "date" },
      { key: "Check_in", header: "Check In", type: "time" },
      { key: "Check_out", header: "Check Out", type: "time" },
      { key: "Working_minutes", header: "Working (min)" },
      { key: "Source", header: "Source", filterable: true },
      { key: "Attendance_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Attendance_date", label: "Attendance Date", type: "date", required: true },
      { name: "Check_in", label: "Check In", type: "time" },
      { name: "Check_out", label: "Check Out", type: "time" },
      { name: "Working_minutes", label: "Working Minutes", type: "number" },
      {
        name: "Source",
        label: "Source",
        type: "select",
        options: [...ATTENDANCE_SOURCE_TYPES],
      },
      {
        name: "Attendance_status",
        label: "Status",
        type: "select",
        options: [...ATTENDANCE_STATUS_OPTIONS],
        required: true,
      },
      { name: "Remarks", label: "Remarks", type: "textarea", span: "full" },
    ],
  },
  "daily-attendance": {
    id: "daily-attendance",
    title: "Daily Attendance",
    section: "Attendance Management",
    tableName: "trans_attendance",
    usesApi: true,
    actionLabel: "Mark Attendance",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Employee_code", "Attendance_date", "Shift_name"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Attendance_date", header: "Date", type: "date" },
      { key: "Shift_name", header: "Shift", filterable: true },
      { key: "Check_in", header: "Check In", type: "time" },
      { key: "Check_out", header: "Check Out", type: "time" },
      { key: "Working_minutes", header: "Working", type: "duration" },
      { key: "Late_minutes", header: "Late", type: "duration" },
      { key: "Early_departure_minutes", header: "Early", type: "duration" },
      { key: "Attendance_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Attendance_date", label: "Date", type: "date", required: true },
      { name: "Shift_name", label: "Shift", type: "select", options: ["General Shift", "Night Shift"] },
      { name: "Check_in", label: "Check In", type: "time" },
      { name: "Check_out", label: "Check Out", type: "time" },
      { name: "Working_minutes", label: "Working Minutes", type: "number" },
      { name: "Late_minutes", label: "Late Minutes", type: "number" },
      { name: "Early_departure_minutes", label: "Early Departure (min)", type: "number" },
      {
        name: "Source",
        label: "Source",
        type: "select",
        options: [...ATTENDANCE_SOURCE_TYPES],
      },
      {
        name: "Attendance_status",
        label: "Status",
        type: "select",
        options: [...ATTENDANCE_STATUS_OPTIONS],
        required: true,
      },
    ],
  },
  "monthly-attendance": {
    id: "monthly-attendance",
    title: "Monthly Attendance",
    section: "Attendance Management",
    tableName: "trans_attendance_monthly",
    actionLabel: "Generate Summary",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Employee_code", "Month_year"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Month_year", header: "Month", filterable: true },
      { key: "Present_days", header: "Present" },
      { key: "Absent_days", header: "Absent" },
      { key: "Half_day_days", header: "Half Day" },
      { key: "Late_days", header: "Late" },
      { key: "Overtime_hours", header: "OT (hrs)" },
      { key: "Attendance_status", header: "Summary", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Month_year", label: "Month", placeholder: "Aug 2026", required: true },
      { name: "Present_days", label: "Present Days", type: "number" },
      { name: "Absent_days", label: "Absent Days", type: "number" },
      { name: "Half_day_days", label: "Half Days", type: "number" },
      { name: "Late_days", label: "Late Days", type: "number" },
      { name: "Overtime_hours", label: "Overtime Hours", type: "number" },
      {
        name: "Attendance_status",
        label: "Summary Status",
        type: "select",
        options: ["Complete", "Pending", "Under Review"],
        defaultValue: "Complete",
      },
    ],
  },
  "attendance-processing": {
    id: "attendance-processing",
    title: "Attendance Processing",
    section: "Attendance Management",
    tableName: "trans_attendance_processing",
    actionLabel: "Run Processing",
    nameKey: "Batch_name",
    searchKeys: ["Batch_name", "Process_type", "Period"],
    columns: [
      { key: "Batch_name", header: "Batch" },
      { key: "Process_type", header: "Process", filterable: true },
      { key: "Period", header: "Period" },
      { key: "Records_processed", header: "Records" },
      { key: "Processed_on", header: "Processed On", type: "date" },
      { key: "Attendance_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Batch_name", label: "Batch Name", required: true, placeholder: "Aug-2026-Daily" },
      {
        name: "Process_type",
        label: "Process Type",
        type: "select",
        options: [
          "Daily sync",
          "Monthly close",
          "Missing punch fix",
          "Overtime calculation",
          "Regularization apply",
        ],
        required: true,
      },
      { name: "Period", label: "Period", placeholder: "Aug 2026", required: true },
      { name: "Records_processed", label: "Records Processed", type: "number" },
      { name: "Processed_on", label: "Processed On", type: "date" },
      {
        name: "Attendance_status",
        label: "Status",
        type: "select",
        options: ["Completed", "Running", "Failed", "Queued"],
        defaultValue: "Queued",
      },
    ],
  },
  "attendance-calendar": {
    id: "attendance-calendar",
    title: "Attendance Calendar",
    section: "Attendance Management",
    tableName: "mst_attendance_calendar",
    actionLabel: "Add Calendar Entry",
    nameKey: "Calendar_title",
    searchKeys: ["Calendar_title", "Calendar_date", "Day_type"],
    columns: [
      { key: "Calendar_date", header: "Date", type: "date" },
      { key: "Calendar_title", header: "Title" },
      { key: "Day_type", header: "Day Type", filterable: true },
      { key: "Branch_Name", header: "Branch", filterable: true },
      { key: "Attendance_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Calendar_date", label: "Date", type: "date", required: true },
      { name: "Calendar_title", label: "Title", required: true },
      {
        name: "Day_type",
        label: "Day Type",
        type: "select",
        options: ["Working Day", "Holiday", "Weekly Off", "Half Day", "On-Duty"],
        required: true,
      },
      {
        name: "Branch_Name",
        label: "Branch",
        type: "select",
        options: ["All Branches", "Head Office", "Branch 1"],
      },
      {
        name: "Attendance_status",
        label: "Status",
        type: "select",
        options: ["Active", "Inactive"],
        defaultValue: "Active",
      },
    ],
  },
  "attendance-sources": {
    id: "attendance-sources",
    title: "Attendance Sources",
    section: "Attendance Management",
    tableName: "mst_attendance_source",
    actionLabel: "Configure Source",
    nameKey: "Source_name",
    searchKeys: ["Source_name", "Integration_type"],
    columns: [
      { key: "Source_name", header: "Source" },
      { key: "Integration_type", header: "Type", filterable: true },
      { key: "Endpoint_or_device", header: "Endpoint / Device" },
      { key: "Last_sync_time", header: "Last Sync" },
      { key: "Attendance_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      {
        name: "Source_name",
        label: "Source",
        type: "select",
        options: [...ATTENDANCE_SOURCE_TYPES],
        required: true,
      },
      {
        name: "Integration_type",
        label: "Integration Type",
        type: "select",
        options: ["Device", "Mobile App", "Web Portal", "Manual Entry", "REST API"],
        required: true,
      },
      {
        name: "Endpoint_or_device",
        label: "Endpoint / Device",
        placeholder: "Device-01 or https://api.example.com/attendance",
        span: "full",
      },
      { name: "Last_sync_time", label: "Last Sync Time", placeholder: "2026-08-28 09:00" },
      {
        name: "Is_enabled",
        label: "Source enabled",
        type: "checkbox",
        defaultValue: "1",
        span: "full",
      },
      {
        name: "Attendance_status",
        label: "Status",
        type: "select",
        options: ["Active", "Inactive"],
        defaultValue: "Active",
      },
    ],
  },
  "attendance-register": {
    id: "attendance-register",
    title: "Attendance Register",
    section: "Attendance Management",
    tableName: "trans_attendance",
    actionLabel: "Add Entry",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Employee_code", "Attendance_date", "Source"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Attendance_date", header: "Date", type: "date" },
      { key: "Working_minutes", header: "Working (min)" },
      { key: "Overtime_minutes", header: "OT (min)" },
      { key: "Source", header: "Source", filterable: true },
      { key: "Attendance_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Attendance_date", label: "Date", type: "date", required: true },
      { name: "Working_minutes", label: "Working Minutes", type: "number" },
      { name: "Overtime_minutes", label: "Overtime Minutes", type: "number" },
      {
        name: "Source",
        label: "Source",
        type: "select",
        options: [...ATTENDANCE_SOURCE_TYPES],
      },
      {
        name: "Attendance_status",
        label: "Status",
        type: "select",
        options: [...ATTENDANCE_STATUS_OPTIONS],
        required: true,
      },
    ],
  },
  "check-in-out": {
    id: "check-in-out",
    title: "Check-in / Check-out",
    section: "Attendance Management",
    tableName: "trans_attendance_punch",
    actionLabel: "Add Punch",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Punch_time", "Punch_type", "Source"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Punch_time", header: "Punch Time" },
      { key: "Punch_type", header: "Punch Type", filterable: true },
      { key: "Source", header: "Source", filterable: true },
      { key: "Device_name", header: "Device" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Punch_time", label: "Punch Time", type: "time", required: true },
      {
        name: "Punch_type",
        label: "Punch Type",
        type: "select",
        options: ["Check-in", "Check-out", "In", "Out", "Unknown"],
        required: true,
      },
      {
        name: "Source",
        label: "Source",
        type: "select",
        options: [...ATTENDANCE_SOURCE_TYPES],
      },
      { name: "Device_name", label: "Device" },
    ],
  },
  regularization: {
    id: "regularization",
    title: "Attendance Regularization",
    section: "Attendance Management",
    tableName: "trans_attendance",
    actionLabel: "Request Regularization",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Attendance_date"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Attendance_date", header: "Date", type: "date" },
      { key: "Check_in", header: "Requested In", type: "time" },
      { key: "Check_out", header: "Requested Out", type: "time" },
      { key: "Remarks", header: "Reason" },
      { key: "Attendance_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Attendance_date", label: "Date", type: "date", required: true },
      { name: "Check_in", label: "Requested Check In", type: "time" },
      { name: "Check_out", label: "Requested Check Out", type: "time" },
      { name: "Remarks", label: "Reason", type: "textarea", span: "full", required: true },
    ],
  },
  "missing-punch": {
    id: "missing-punch",
    title: "Missing Punch",
    section: "Attendance Management",
    tableName: "trans_attendance_punch",
    actionLabel: "Add Missing Punch",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Punch_time", header: "Expected Punch" },
      { key: "Punch_type", header: "Missing Type" },
      { key: "Source", header: "Source", filterable: true },
      { key: "Attendance_status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Punch_time", label: "Expected Punch Time", type: "time", required: true },
      { name: "Punch_type", label: "Missing Punch Type", type: "select", options: ["In", "Out"], required: true },
      { name: "Remarks", label: "Remarks", type: "textarea", span: "full" },
    ],
  },
  overtime: {
    id: "overtime",
    title: "Overtime",
    section: "Attendance Management",
    tableName: "trans_attendance",
    actionLabel: "Add Overtime",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Attendance_date", header: "Date", type: "date" },
      { key: "Overtime_minutes", header: "OT Minutes" },
      { key: "Shift_name", header: "Shift", filterable: true },
      { key: "Remarks", header: "Remarks" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Attendance_date", label: "Date", type: "date", required: true },
      { name: "Overtime_minutes", label: "Overtime Minutes", type: "number", required: true },
      { name: "Remarks", label: "Remarks", type: "textarea", span: "full" },
    ],
  },
  "attendance-shifts": {
    id: "attendance-shifts",
    title: "Shift Management",
    section: "Attendance Management",
    tableName: "trans_employee_shift",
    actionLabel: "Assign Shift",
    nameKey: "Employee_name",
    searchKeys: ["Employee_name", "Shift_name"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Shift_name", header: "Shift", filterable: true },
      { key: "From_date", header: "From Date", type: "date" },
      { key: "To_date", header: "To Date", type: "date" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", options: ["EMP-1001", "EMP-1002"], required: true },
      { name: "Shift_name", label: "Shift", type: "select", options: ["General Shift", "Night Shift"], required: true },
      { name: "From_date", label: "From Date", type: "date", required: true },
      { name: "To_date", label: "To Date", type: "date" },
    ],
  },
  "attendance-rules": {
    id: "attendance-rules",
    title: "Attendance Rules",
    section: "Attendance Management",
    tableName: "mst_attendance_rule",
    actionLabel: "Add Rule",
    nameKey: "Rule_name",
    modalSize: "xl",
    searchKeys: ["Rule_name", "Shift_name"],
    columns: [
      { key: "Rule_name", header: "Rule Name" },
      { key: "Shift_name", header: "Shift", filterable: true },
      { key: "Grace_minutes", header: "Grace (min)" },
      { key: "Late_threshold_minutes", header: "Late (min)" },
      { key: "Min_working_hours", header: "Min Hours" },
      { key: "Overtime_after", header: "OT After (hrs)" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formSections: ATTENDANCE_RULE_FORM_SECTIONS,
  },
  "on-duty": {
    id: "on-duty",
    title: "On-Duty",
    section: "Attendance Management",
    tableName: "trans_employee_on_duty",
    actionLabel: "Assign On-Duty",
    nameKey: "Employee_name",
    modalSize: "lg",
    searchKeys: ["Employee_name", "Employee_code", "Duty_location"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Duty_date", header: "Duty Date", type: "date" },
      { key: "Duty_location", header: "Location", filterable: true },
      { key: "From_time", header: "From", type: "time" },
      { key: "To_time", header: "To", type: "time" },
      { key: "Attendance_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Duty_date", label: "Duty Date", type: "date", required: true },
      { name: "Duty_location", label: "Location", required: true, placeholder: "Client site / branch" },
      { name: "From_time", label: "From Time", type: "time", required: true },
      { name: "To_time", label: "To Time", type: "time", required: true },
      { name: "Remarks", label: "Remarks", type: "textarea", span: "full" },
      {
        name: "Attendance_status",
        label: "Status",
        type: "select",
        options: ["Scheduled", "On-Duty", "Completed", "Cancelled"],
        defaultValue: "Scheduled",
      },
    ],
  },
  holidays: {
    id: "holidays",
    title: "Holidays",
    section: "Attendance Management",
    tableName: "mst_holiday",
    actionLabel: "Add Holiday",
    nameKey: "Holiday_name",
    usesApi: true,
    statusToggle: false,
    searchKeys: ["Holiday_name", "Holiday_date"],
    columns: [
      { key: "Holiday_date", header: "Date", type: "date" },
      { key: "Holiday_name", header: "Holiday Name" },
      { key: "Holiday_type", header: "Type", filterable: true },
      // { key: "Is_optional", header: "Optional", type: "boolean" },
    ],
    formFields: [
      { name: "Holiday_date", label: "Holiday Date", type: "date", required: true },
      { name: "Holiday_name", label: "Holiday Name", required: true },
      {
        name: "Holiday_type",
        label: "Holiday Type",
        type: "select",
        options: ["NATIONAL", "FESTIVAL", "REGIONAL", "OPTIONAL", "OTHER"],
        required: true,
      },
      // { name: "Is_optional", label: "Optional Holiday", type: "checkbox" },
    ],
  },
  "weekly-off": {
    id: "weekly-off",
    title: "Weekly Off",
    section: "Attendance Management",
    tableName: "mst_work_shift",
    actionLabel: "Add Weekly Off",
    nameKey: "Day_name",
    searchKeys: ["Day_name", "Branch_Name"],
    columns: [
      { key: "Day_name", header: "Day" },
      { key: "Branch_Name", header: "Branch", filterable: true },
      { key: "Off_type", header: "Off Type", filterable: true },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      {
        name: "Day_name",
        label: "Weekly Off Day",
        type: "select",
        options: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        required: true,
      },
      { name: "Branch_Name", label: "Branch", type: "select", options: ["All Branches", "Head Office", "Branch 1"] },
      { name: "Off_type", label: "Off Type", type: "select", options: ["Full Day", "Alternate Saturday"] },
      { name: "Status", label: "Status", type: "select", options: statusOptions },
    ],
  },
  "leave-master": {
    id: "leave-master",
    title: "Leave Master",
    section: "Leave Management",
    tableName: "mst_leave_type",
    actionLabel: "Add Leave Type",
    nameKey: "Leave_name",
    modalSize: "lg",
    searchKeys: ["Leave_code", "Leave_name", "Leave_category"],
    columns: [
      { key: "Leave_code", header: "Code" },
      { key: "Leave_name", header: "Leave Type" },
      { key: "Leave_category", header: "Category", filterable: true },
      { key: "Annual_quota", header: "Annual Quota" },
      { key: "Carry_forward", header: "Carry Forward" },
      { key: "Encashable", header: "Encashable" },
      { key: "Requires_document", header: "Document Required" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Leave_code", label: "Leave Code", required: true, placeholder: "e.g. CL" },
      { name: "Leave_name", label: "Leave Name", required: true, placeholder: "e.g. Casual Leave" },
      {
        name: "Leave_category",
        label: "Category",
        type: "select",
        options: ["Paid", "Unpaid"],
        defaultValue: "Paid",
        required: true,
      },
      { name: "Annual_quota", label: "Annual Quota (Days)", type: "number", defaultValue: "12" },
      {
        name: "Carry_forward",
        label: "Carry Forward",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "No",
      },
      {
        name: "Encashable",
        label: "Encashable",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "No",
      },
      {
        name: "Requires_document",
        label: "Requires Supporting Document",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "No",
      },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: activeInactive,
        defaultValue: "Active",
      },
    ],
  },
  "leave-policy": {
    id: "leave-policy",
    title: "Leave Policy",
    section: "Leave Management",
    tableName: "mst_leave_policy",
    actionLabel: "Add Policy",
    nameKey: "Policy_name",
    modalSize: "lg",
    searchKeys: ["Policy_name", "Leave_type", "Applicable_to"],
    columns: [
      { key: "Policy_name", header: "Policy Name" },
      { key: "Leave_type", header: "Leave Type", filterable: true },
      { key: "Applicable_to", header: "Applicable To", filterable: true },
      { key: "Min_days_notice", header: "Min Notice (Days)" },
      { key: "Max_consecutive_days", header: "Max Consecutive" },
      { key: "Sandwich_rule", header: "Sandwich Rule" },
      { key: "Half_day_allowed", header: "Half Day" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Policy_name", label: "Policy Name", required: true },
      { name: "Leave_type", label: "Leave Type", type: "select", required: true },
      {
        name: "Applicable_to",
        label: "Applicable To",
        type: "select",
        options: ["All Employees", "Department", "Grade", "Employment Type"],
        defaultValue: "All Employees",
        required: true,
      },
      { name: "Min_days_notice", label: "Minimum Notice (Days)", type: "number", defaultValue: "1" },
      { name: "Max_consecutive_days", label: "Max Consecutive Days", type: "number", defaultValue: "5" },
      {
        name: "Sandwich_rule",
        label: "Sandwich Rule",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "No",
      },
      {
        name: "Half_day_allowed",
        label: "Half Day Allowed",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "Yes",
      },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: activeInactive,
        defaultValue: "Active",
      },
    ],
  },
  "leave-allocation": {
    id: "leave-allocation",
    title: "Leave Allocation",
    section: "Leave Management",
    tableName: "trans_leave_allocation",
    actionLabel: "Allocate Leave",
    nameKey: "Employee_name",
    modalSize: "lg",
    searchKeys: ["Employee_name", "Employee_code", "Leave_type", "Year"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Leave_type", header: "Leave Type", filterable: true },
      { key: "Year", header: "Year", filterable: true },
      { key: "Allocated_days", header: "Allocated" },
      { key: "Used_days", header: "Used" },
      { key: "Balance_days", header: "Balance" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Leave_type", label: "Leave Type", type: "select", required: true },
      { name: "Year", label: "Year", defaultValue: "2026", required: true },
      { name: "Allocated_days", label: "Allocated Days", type: "number", required: true },
      { name: "Used_days", label: "Used Days", type: "number", defaultValue: "0" },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: activeInactive,
        defaultValue: "Active",
      },
    ],
  },
  "leave-application": {
    id: "leave-application",
    title: "Leave Application",
    section: "Leave Management",
    tableName: "trans_leave_application",
    actionLabel: "Apply Leave",
    nameKey: "Employee_name",
    modalSize: "lg",
    searchKeys: ["Employee_name", "Employee_code", "Leave_type", "Application_status"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Leave_type", header: "Leave Type", filterable: true },
      { key: "From_date", header: "From Date", type: "date" },
      { key: "To_date", header: "To Date", type: "date" },
      { key: "Number_of_days", header: "Days" },
      { key: "Reason", header: "Reason" },
      { key: "Document_name", header: "Document" },
      { key: "Application_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Leave_type", label: "Leave Type", type: "select", required: true },
      { name: "From_date", label: "From Date", type: "date", required: true },
      { name: "To_date", label: "To Date", type: "date", required: true },
      { name: "Number_of_days", label: "Number of Days", type: "number", required: true },
      { name: "Reason", label: "Reason", type: "textarea", span: "full", required: true },
      {
        name: "Supporting_document",
        label: "Supporting Document",
        type: "file",
        accept: ".pdf,.jpg,.jpeg,.png,.doc,.docx",
        maxSizeMb: 5,
        hint: "PDF, JPG, PNG, DOC · max 5 MB · optional unless required by leave type",
        fileNameKey: "Document_name",
      },
    ],
  },
  "leave-approval": {
    id: "leave-approval",
    title: "Leave Approval",
    section: "Leave Management",
    tableName: "trans_leave_approval",
    actionLabel: "Add Approval Record",
    nameKey: "Employee_name",
    modalSize: "lg",
    searchKeys: ["Employee_name", "Employee_code", "Leave_type", "Approval_status"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Leave_type", header: "Leave Type", filterable: true },
      { key: "From_date", header: "From Date", type: "date" },
      { key: "To_date", header: "To Date", type: "date" },
      { key: "Number_of_days", header: "Days" },
      { key: "Applied_on", header: "Applied On", type: "date" },
      { key: "Approver_name", header: "Approver" },
      { key: "Approval_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Leave_type", label: "Leave Type", type: "select", required: true },
      { name: "From_date", label: "From Date", type: "date", required: true },
      { name: "To_date", label: "To Date", type: "date", required: true },
      { name: "Number_of_days", label: "Number of Days", type: "number", required: true },
      { name: "Applied_on", label: "Applied On", type: "date", required: true },
      { name: "Approver_name", label: "Approver", defaultValue: "Reporting Manager" },
      {
        name: "Approval_status",
        label: "Approval Status",
        type: "select",
        options: ["Pending", "Approved", "Rejected"],
        defaultValue: "Pending",
        required: true,
      },
      { name: "Remarks", label: "Remarks", type: "textarea", span: "full" },
    ],
  },
  "leave-calendar": {
    id: "leave-calendar",
    title: "Leave Calendar",
    section: "Leave Management",
    tableName: "trans_leave_calendar",
    actionLabel: "Add Calendar Entry",
    nameKey: "Employee_name",
    modalSize: "lg",
    searchKeys: ["Employee_name", "Employee_code", "Leave_type", "Calendar_month", "Leave_status"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Leave_type", header: "Leave Type", filterable: true },
      { key: "From_date", header: "From Date", type: "date" },
      { key: "To_date", header: "To Date", type: "date" },
      { key: "Number_of_days", header: "Days" },
      { key: "Calendar_month", header: "Month", filterable: true },
      { key: "Leave_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Leave_type", label: "Leave Type", type: "select", required: true },
      { name: "From_date", label: "From Date", type: "date", required: true },
      { name: "To_date", label: "To Date", type: "date", required: true },
      { name: "Number_of_days", label: "Number of Days", type: "number", required: true },
      { name: "Calendar_month", label: "Calendar Month", placeholder: "Aug 2026" },
      {
        name: "Leave_status",
        label: "Status",
        type: "select",
        options: ["Approved", "Pending", "Cancelled"],
        defaultValue: "Approved",
      },
    ],
  },
  "leave-encashment": {
    id: "leave-encashment",
    title: "Leave Encashment",
    section: "Leave Management",
    tableName: "trans_leave_encashment",
    actionLabel: "Request Encashment",
    nameKey: "Employee_name",
    modalSize: "lg",
    searchKeys: ["Employee_name", "Employee_code", "Leave_type", "Request_status"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Leave_type", header: "Leave Type", filterable: true },
      { key: "Encashment_year", header: "Year", filterable: true },
      { key: "Days_to_encash", header: "Days" },
      { key: "Per_day_rate", header: "Per Day Rate", type: "currency" },
      { key: "Encashment_amount", header: "Amount", type: "currency" },
      { key: "Request_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Leave_type", label: "Leave Type", type: "select", required: true },
      { name: "Encashment_year", label: "Year", defaultValue: "2026", required: true },
      { name: "Days_to_encash", label: "Days to Encash", type: "number", required: true },
      { name: "Per_day_rate", label: "Per Day Rate", type: "number", required: true },
      {
        name: "Request_status",
        label: "Status",
        type: "select",
        options: ["Pending", "Approved", "Rejected", "Paid"],
        defaultValue: "Pending",
      },
    ],
  },
  "payroll-salary-components": {
    id: "payroll-salary-components",
    title: "Salary Components",
    section: "Payroll Management",
    tableName: "mst_salary_component",
    actionLabel: "Add Component",
    nameKey: "Component_name",
    modalSize: "xl",
    searchKeys: ["Component_code", "Component_name", "Component_type", "Calculation_type"],
    columns: [
      { key: "Component_code", header: "Code" },
      { key: "Component_name", header: "Component" },
      { key: "Component_type", header: "Type", filterable: true },
      { key: "Calculation_type", header: "Calculation", filterable: true },
      { key: "Default_value", header: "Default", type: "currency" },
      { key: "PF_applicable", header: "PF" },
      { key: "ESI_applicable", header: "ESI" },
      { key: "PT_applicable", header: "PT" },
      { key: "TDS_applicable", header: "TDS" },
      { key: "Status", header: "Status", type: "status" },
    ],
    formFields: [
      { name: "Component_code", label: "Component Code", required: true, placeholder: "e.g. BASIC" },
      { name: "Component_name", label: "Component Name", required: true },
      {
        name: "Component_type",
        label: "Component Type",
        type: "select",
        options: ["Earning", "Deduction"],
        required: true,
      },
      {
        name: "Calculation_type",
        label: "Calculation Type",
        type: "select",
        options: [
          "Fixed Amount",
          "Percentage of Basic",
          "Percentage of Gross",
          "Attendance Based",
          "Formula",
        ],
        defaultValue: "Fixed Amount",
        required: true,
      },
      { name: "Default_value", label: "Default Value / %", type: "number", defaultValue: "0" },
      {
        name: "PF_applicable",
        label: "PF Applicable",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "No",
      },
      {
        name: "ESI_applicable",
        label: "ESI Applicable",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "No",
      },
      {
        name: "PT_applicable",
        label: "Professional Tax Applicable",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "No",
      },
      {
        name: "TDS_applicable",
        label: "TDS Applicable",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "No",
      },
      {
        name: "Taxable",
        label: "Taxable",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "Yes",
      },
      { name: "Display_order", label: "Display Order", type: "number", defaultValue: "1" },
      {
        name: "Status",
        label: "Status",
        type: "select",
        options: activeInactive,
        defaultValue: "Active",
      },
    ],
  },
  "payroll-salary-structure": {
    id: "payroll-salary-structure",
    title: "Salary Structure",
    section: "Payroll Management",
    tableName: "mst_salary_structure",
    actionLabel: "Add Structure",
    nameKey: "Structure_name",
    modalSize: "xl",
    searchKeys: ["Structure_code", "Structure_name", "Component_name", "Applicable_to"],
    columns: [
      { key: "Structure_name", header: "Structure" },
      { key: "Component_name", header: "Component", filterable: true },
      { key: "Component_type", header: "Type", filterable: true },
      { key: "Amount_type", header: "Amount Type" },
      { key: "Amount_value", header: "Value" },
      { key: "Computed_amount", header: "Amount", type: "currency" },
      { key: "Gross_salary", header: "Gross", type: "currency" },
      { key: "Net_salary", header: "Net", type: "currency" },
      { key: "Statutory_rule_set", header: "Statutory Rules", filterable: true },
      { key: "Status", header: "Status", type: "status" },
    ],
    formSections: [
      {
        id: "structure-info",
        title: "Structure Details",
        fields: [
          { name: "Structure_code", label: "Structure Code", required: true },
          { name: "Structure_name", label: "Structure Name", required: true },
          {
            name: "Applicable_to",
            label: "Applicable To",
            type: "select",
            options: ["All Employees", "Grade", "Designation", "Department"],
            defaultValue: "All Employees",
          },
          { name: "Component_name", label: "Component", type: "select", required: true },
          {
            name: "Amount_type",
            label: "Amount Type",
            type: "select",
            options: ["Fixed", "Percentage of Basic", "Percentage of Gross"],
            defaultValue: "Fixed",
          },
          { name: "Amount_value", label: "Amount / %", type: "number", required: true },
          { name: "Effective_from", label: "Effective From", type: "date", required: true },
          {
            name: "Statutory_rule_set",
            label: "Statutory Rule Set",
            type: "select",
            options: ["India - Default", "India - Karnataka PT", "India - Maharashtra PT", "Custom"],
            defaultValue: "India - Default",
          },
        ],
      },
      {
        id: "earnings",
        title: "Earnings",
        description: "Configure earning components for this structure.",
        fields: [
          { name: "Basic_salary", label: "Basic Salary", type: "number", required: true },
          { name: "HRA", label: "HRA", type: "number" },
          { name: "Conveyance", label: "Conveyance", type: "number" },
          { name: "Medical_allowance", label: "Medical Allowance", type: "number" },
          { name: "Special_allowance", label: "Special Allowance", type: "number" },
          { name: "Other_allowances", label: "Other Allowances", type: "number" },
          { name: "Incentives", label: "Incentives", type: "number" },
          { name: "Bonus", label: "Bonus", type: "number" },
          { name: "Overtime", label: "Overtime", type: "number" },
        ],
      },
      {
        id: "deductions",
        title: "Deductions",
        description: "Statutory and other deductions — configurable per applicable rules.",
        fields: [
          { name: "PF", label: "PF", type: "number" },
          { name: "ESI", label: "ESI", type: "number" },
          { name: "Professional_tax", label: "Professional Tax", type: "number" },
          { name: "TDS", label: "TDS", type: "number" },
          { name: "Loan_recovery", label: "Loan Recovery", type: "number" },
          { name: "Advance_recovery", label: "Advance Recovery", type: "number" },
          { name: "Leave_without_pay", label: "Leave Without Pay", type: "number" },
          { name: "Other_deductions", label: "Other Deductions", type: "number" },
        ],
      },
    ],
  },
  "payroll-salary-revision": {
    id: "payroll-salary-revision",
    title: "Salary Revision",
    section: "Payroll Management",
    tableName: "trans_salary_revision",
    actionLabel: "Add Revision",
    nameKey: "Employee_name",
    modalSize: "lg",
    searchKeys: ["Employee_name", "Employee_code", "Revision_type", "Revision_status"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Salary_structure", header: "Structure", filterable: true },
      { key: "Revision_type", header: "Type", filterable: true },
      { key: "Old_gross", header: "Old Gross", type: "currency" },
      { key: "New_gross", header: "New Gross", type: "currency" },
      { key: "Increment_percent", header: "Increment %" },
      { key: "Effective_date", header: "Effective Date", type: "date" },
      { key: "Revision_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Salary_structure", label: "Salary Structure", type: "select", required: true },
      {
        name: "Revision_type",
        label: "Revision Type",
        type: "select",
        options: ["Annual Increment", "Promotion", "Market Correction", "Full & Final"],
        defaultValue: "Annual Increment",
        required: true,
      },
      { name: "Old_basic", label: "Old Basic", type: "number", required: true },
      { name: "New_basic", label: "New Basic", type: "number", required: true },
      { name: "Old_gross", label: "Old Gross", type: "number", required: true },
      { name: "New_gross", label: "New Gross", type: "number", required: true },
      { name: "Effective_date", label: "Effective Date", type: "date", required: true },
      { name: "Reason", label: "Reason", type: "textarea", span: "full", required: true },
      { name: "Approved_by", label: "Approved By", defaultValue: "HR Manager" },
      {
        name: "Revision_status",
        label: "Status",
        type: "select",
        options: ["Pending", "Approved", "Rejected"],
        defaultValue: "Pending",
      },
    ],
  },
  "payroll-processing": {
    id: "payroll-processing",
    title: "Payroll Processing",
    section: "Payroll Management",
    tableName: "trans_payroll_processing",
    actionLabel: "Run Payroll",
    nameKey: "Payroll_month",
    modalSize: "lg",
    searchKeys: ["Payroll_month", "Pay_period", "Process_status"],
    columns: [
      { key: "Payroll_month", header: "Month", filterable: true },
      { key: "Pay_period", header: "Pay Period" },
      { key: "Employees_count", header: "Employees" },
      { key: "Gross_pay", header: "Gross Pay", type: "currency" },
      { key: "Total_deductions", header: "Deductions", type: "currency" },
      { key: "Net_pay", header: "Net Pay", type: "currency" },
      { key: "PF_total", header: "PF", type: "currency" },
      { key: "ESI_total", header: "ESI", type: "currency" },
      { key: "Process_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Payroll_month", label: "Payroll Month", placeholder: "Aug 2026", required: true },
      { name: "Pay_period", label: "Pay Period", placeholder: "01-Aug-2026 to 31-Aug-2026", required: true },
      { name: "Employees_count", label: "Employees Count", type: "number", required: true },
      { name: "Gross_pay", label: "Gross Pay", type: "number", required: true },
      { name: "Total_deductions", label: "Total Deductions", type: "number", required: true },
      { name: "PF_total", label: "PF Total", type: "number" },
      { name: "ESI_total", label: "ESI Total", type: "number" },
      { name: "PT_total", label: "Professional Tax Total", type: "number" },
      { name: "TDS_total", label: "TDS Total", type: "number" },
      {
        name: "Statutory_rule_set",
        label: "Statutory Rule Set",
        type: "select",
        options: ["India - Default", "India - Karnataka PT", "India - Maharashtra PT", "Custom"],
        defaultValue: "India - Default",
      },
      {
        name: "Process_status",
        label: "Status",
        type: "select",
        options: ["Draft", "Processing", "Completed", "Failed"],
        defaultValue: "Draft",
      },
      { name: "Processed_on", label: "Processed On", type: "date" },
      { name: "Processed_by", label: "Processed By", defaultValue: "Payroll Executive" },
    ],
  },
  "payroll-finalization": {
    id: "payroll-finalization",
    title: "Payroll Finalization",
    section: "Payroll Management",
    tableName: "trans_payroll_finalization",
    actionLabel: "Finalize Payroll",
    nameKey: "Batch_ref",
    modalSize: "lg",
    searchKeys: ["Payroll_month", "Batch_ref", "Finalization_status"],
    columns: [
      { key: "Payroll_month", header: "Month", filterable: true },
      { key: "Batch_ref", header: "Batch Ref" },
      { key: "Employees_count", header: "Employees" },
      { key: "Gross_pay", header: "Gross Pay", type: "currency" },
      { key: "Net_pay", header: "Net Pay", type: "currency" },
      { key: "PF_amount", header: "PF", type: "currency" },
      { key: "ESI_amount", header: "ESI", type: "currency" },
      { key: "PT_amount", header: "PT", type: "currency" },
      { key: "TDS_amount", header: "TDS", type: "currency" },
      { key: "Finalization_status", header: "Status", type: "status", filterable: true },
    ],
    formFields: [
      { name: "Payroll_month", label: "Payroll Month", required: true },
      { name: "Batch_ref", label: "Batch Reference", required: true },
      { name: "Employees_count", label: "Employees Count", type: "number", required: true },
      { name: "Gross_pay", label: "Gross Pay", type: "number", required: true },
      { name: "Net_pay", label: "Net Pay", type: "number", required: true },
      { name: "PF_amount", label: "PF Amount", type: "number" },
      { name: "ESI_amount", label: "ESI Amount", type: "number" },
      { name: "PT_amount", label: "Professional Tax", type: "number" },
      { name: "TDS_amount", label: "TDS Amount", type: "number" },
      { name: "Loan_recovery_total", label: "Loan Recovery", type: "number" },
      { name: "Advance_recovery_total", label: "Advance Recovery", type: "number" },
      {
        name: "Register_generated",
        label: "Payroll Register Generated",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "No",
      },
      {
        name: "Bank_file_generated",
        label: "Bank Payment File Generated",
        type: "select",
        options: ["Yes", "No"],
        defaultValue: "No",
      },
      {
        name: "Finalization_status",
        label: "Status",
        type: "select",
        options: ["Pending", "Finalized", "Reopened"],
        defaultValue: "Pending",
      },
      { name: "Finalized_on", label: "Finalized On", type: "date" },
      { name: "Finalized_by", label: "Finalized By", defaultValue: "Payroll Manager" },
    ],
  },
  "payroll-payslip-bank": {
    id: "payroll-payslip-bank",
    title: "Payslip & Bank Transfer",
    section: "Payroll Management",
    tableName: "trans_payslip_bank",
    actionLabel: "Add Payslip Record",
    nameKey: "Employee_name",
    modalSize: "lg",
    searchKeys: ["Employee_name", "Employee_code", "Payroll_month", "Payslip_status", "Bank_transfer_status"],
    columns: [
      { key: "Employee_name", header: "Employee", type: "person", subtitleKey: "Employee_code" },
      { key: "Payroll_month", header: "Month", filterable: true },
      { key: "Gross_pay", header: "Gross Pay", type: "currency" },
      { key: "Total_deductions", header: "Deductions", type: "currency" },
      { key: "Net_pay", header: "Net Pay", type: "currency" },
      { key: "Payslip_status", header: "Payslip", type: "status", filterable: true },
      { key: "Bank_transfer_status", header: "Bank Transfer", type: "status", filterable: true },
      { key: "UTR_ref", header: "UTR / Ref" },
      { key: "Payment_date", header: "Payment Date", type: "date" },
    ],
    formFields: [
      { name: "Employee_code", label: "Employee", type: "select", required: true },
      { name: "Payroll_month", label: "Payroll Month", required: true },
      { name: "Pay_period", label: "Pay Period" },
      { name: "Gross_pay", label: "Gross Pay", type: "number", required: true },
      { name: "Total_deductions", label: "Total Deductions", type: "number", required: true },
      { name: "Net_pay", label: "Net Pay", type: "number", required: true },
      {
        name: "Payslip_status",
        label: "Payslip Status",
        type: "select",
        options: ["Generated", "Published", "On Hold"],
        defaultValue: "Generated",
      },
      {
        name: "Bank_transfer_status",
        label: "Bank Transfer Status",
        type: "select",
        options: ["Pending", "Processed", "Paid", "Failed"],
        defaultValue: "Pending",
      },
      { name: "Bank_account_no", label: "Bank Account No." },
      { name: "IFSC_code", label: "IFSC Code" },
      { name: "UTR_ref", label: "UTR / Reference No." },
      { name: "Payment_date", label: "Payment Date", type: "date" },
      {
        name: "Settlement_type",
        label: "Settlement Type",
        type: "select",
        options: ["Regular Payroll", "Bonus", "Full & Final Settlement"],
        defaultValue: "Regular Payroll",
      },
    ],
  },
};

export function getHrmsModule(moduleId: string): HrmsModuleConfig {
  const config = HRMS_MODULES[moduleId];
  if (!config) {
    throw new Error(`Unknown HRMS module: ${moduleId}`);
  }
  return config;
}

export function getModuleFilterFields(config: HrmsModuleConfig) {
  return config.columns
    .filter((column) => column.filterable || column.type === "status")
    .map((column) => ({ key: column.key, label: column.header }));
}

export function getModuleFormFields(config: HrmsModuleConfig): FormField[] {
  if (config.formSections?.length) {
    return config.formSections.flatMap((section) => section.fields);
  }
  return config.formFields ?? [];
}
